version: '3.1'
services:
  server:
    build:
      context: ./server
    secrets:
      - mysql-user
      - mysql-password
      - mysql-database
      - jwt-secret
    ports:
      - 8080:8080
    volumes:
      - node_modules:/usr/src/app/node_modules
    network_mode: bridge

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MYSQL_USER_FILE=/run/secrets/mysql-user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql-database
    secrets:
      - mysql-root-password
      - mysql-user
      - mysql-password
      - mysql-database
    volumes:
      - db:/data/db
    network_mode: bridge

  testdb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password
      - MYSQL_USER_FILE=/run/secrets/mysql-user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql-password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql-database
    secrets:
      - mysql-root-password
      - mysql-user
      - mysql-password
      - mysql-database
    volumes:
      - testdb:/data/db
    network_mode: bridge

secrets:
  mysql-root-password:
    file: secrets/mysql-root-password
  mysql-user:
    file: secrets/mysql-user
  mysql-password:
    file: secrets/mysql-password
  mysql-database:
    file: secrets/mysql-database
  jwt-secret:
    file: secrets/jwt-secret

volumes:
  db:
  testdb:
  node_modules:
